config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events do
    Item::SUB_TYPES.keys.each do |subtype|
      st =subtype.to_s.pluralize
      resources st, :controller => :items
    end
    resources :items do
      resources :answers
    end
    get 'by_group/:id', on: :collection, action: :by_group
    get 'by_tutor/:id', on: :collection, action: :by_tutor
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :items
  belongs_to :tutor

  before_save :generate_uid

  def self.update(json)
    logger.info(json.to_s)
    ids = json.map { |x|
      [Event.generate_uid(x["DATE_REG"], x["NAME_PAIR"], x["NAME_AUD"]), x];
    }
    ids = Hash[ids]
    events = Event.includes(:items).where(uid: ids.keys)
    ids.each do |key, value|
      unless events.any? { |x| x.uid == key }
        event = Event.build(value)
        event.save
        events << event
      end
    end
    events
  end

  def to_param
    return uid
  end

  private

  def self.build(record)
    event = Event.new
    event.pair = record["NAME_PAIR"].to_i
    event.date = Date.parse(record["DATE_REG"])
    event.name_aud = record["NAME_AUD"].upcase
    event.name_group = record["NAME_GROUP"].upcase
    event.tutor_id = record["KOD_FIO"].to_i
    event.abbr_disc = record["ABBR_DISC"]
    event.name_stud = record["NAME_STUD"]
    event.reason = record["REASON"]
    event.stud_type_id = record["KOD_STUD"].to_i
    event.info= record["info"]
    return event
  end

  def self.aud_normalize(name_aud)
    Russian::transliterate(name_aud.upcase)
  end

  def generate_uid
    reg_date = date.strftime('%d%m%y')
    self.uid = pair.to_s+reg_date+Event.aud_normalize(name_aud)
  end

  def self.generate_uid(reg_date, name_pair, name_aud)
    reg_date = reg_date.sub('.20', '').sub('.', '')
    name_pair = name_pair.gsub(/\D+/, '')
    name_aud = Event.aud_normalize(name_aud)
    name_pair+reg_date+name_aud
  end


end

app/controllers/events_controller.rb
require 'rqrcode_png'
require 'net/http'

class EventsController < ApplicationController

  has_mobile_fu
  has_mobile_fu_for :show

  before_filter :require_id, except: :index

  def index
    render layout: 'minimal';
  end

  def by_group
    update('grp', params[:id])
    @group = Group.find(params[:id])
    @events = Event.where(name_group: @group.name.upcase, date: [Date.today..1.week.from_now])
                  .eager_load(:items => [:answers])
                  .where('(session_id = ? or session_id is null)', session[:user])
     render :list
  end

  def by_tutor
    update('fio', params[:id])
    #update('fio', params[:id]) if params[:update]
    #@events ||= Event.all.includes(:items)
    @events = Event.where(tutor_id: params[:id], date: [Date.today..1.week.from_now])
                  .eager_load(:items => [:answers])
                  .where('(session_id = ? or session_id is null)', session[:user])
    render :list
  end

  def show
    @event = Event.where(uid: params[:id]).first
       
      respond_to do |f|
      #f.html { render action: 'show' }
      f.html { render layout: 'mobile.html', action: 'show' }
      f.qr { qr }
      f.mobile { render layout: 'mobile.html', action: 'show' }
    end
  end

  def qr_pic(path)
    qr = RQRCode::QRCode.new(path, size: 5, level: :q)
    png = qr.to_img
    png.resize(200, 200)
  end

  helper_method :qr_pic

private

  def require_id
    redirect_to(action: :index) unless params[:id]
  end

  def qr
    @event ||= Event.find(params[:uid])
    path = url_for(@event)
    filepath = "public/qr/#{@event.to_param}.png"
    unless File.exist?(filepath)
      qr = RQRCode::QRCode.new(path, size: 5, level: :q)
      png = qr.to_img
      png.resize(300, 300).save(filepath)
    end
    send_file(filepath)
  end

  def update(param, id)
    url = "http://schedule.sumdu.edu.ua/index/json?id_#{param}=#{id}"
    logger.info(url)
    json = Net::HTTP.get(URI(url))
    data = JSON.parse(json)
    @events = Event.update(data)
  end

end

app/helpers/events_helper.rb
module EventsHelper

end

app/views/events/_show.erb
<% @qr = RQRCode::QRCode.new(root_url+"events/"+event.uid, size: 4, level: :q)%>

<% if in_mobile_view? %>
    <% content_for(:panel_title) do %>
        <%= event.pair %>
        <%= event.abbr_disc %>
        <%= event.name_aud %>
    <% end %>
<% else %>
  <span class="card-title black-text">
    
    <a class="modal-trigger" href="#modal<%= event.id %>"><%=fa_icon('share-square-o', class: 'fa-2x')%></a>
<!-- Modal Structure -->
    <div id="modal<%= event.id %>" class="modal">
      <div class="modal-content">
        <h5>
          <%= event.pair %>
          <%= event.abbr_disc %>
          <%= event.name_aud %>
        </h5>
        <div class="row">
          <div class="col s5">
            <table>
              <% @qr.modules.each_index do |x| %>
                <tr>  
                <% @qr.modules.each_index do |y| %>
                  <% if @qr.dark?(x,y) %>
                    <td class="black"/>
                  <% else %>
                    <td class="white"/>
                  <% end %>
                <% end %>
                </tr>
              <% end %>
            </table>
          </div>
          <div class="col s7">
            <div class="row">
              <p class="center-align">Copy the link to the ivent</p>
              <div class="input-field">
                <input value="<%= root_url+"events/"+event.uid %>" type="url" onfocus="this.select()">
              </div>
              <p class="center-align">or</p>
                <center><a href="<%= event_path(event, :format => 'qr') %>" class="waves-effect waves-light btn">Download qr code</a></center>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <a class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
      </div>
    </div>
<!-- End Modal Structure -->
    
        <%= event.pair %>
        <%= event.abbr_disc %>
        <%= event.name_aud %>
  </span>
<% end %>
<% unless event.items.blank? %>
    <ul class='collection'>
      <% event.items.each do |item| %>
          <li class="collection-item">
            <%= render partial: "/items/#{item.type.downcase}/show", locals: {item: item} %>
          </li>
      <% end %>
    </ul>
<% else %>
    <ul class='collection'></ul>
<% end %>

app/views/events/index.erb
<div class='row' >
  <div class='col s6 center'>
      <span class="fa-stack fa-5x">
          <i class="fa fa-circle fa-stack-2x" style="color:#ff5722"></i>
          <i class="fa fa-group fa-inverse fa-stack-1x"></i>
      </span><br/>
    <%= select_tag "groups", options_from_collection_for_select(Group.all, "id", "name") %>
  </div>
  <div class='col s6 center'>
      <span class="fa-stack fa-5x">
          <i class="fa fa-circle fa-stack-2x" style="color:#03a9f4"></i>
          <i class="fa fa-user fa-inverse fa-stack-1x"></i>
      </span><br/>
    <%= select_tag "tutors", options_from_collection_for_select(Tutor.all, "id", "name") %>
  </div>
</div>

<script>
    $(function () {
        $("#groups").select2().on('change', function (e) {
            document.location = '/events/by_group/' + e.val;
        });
        $("#tutors").select2().on('change', function (e) {
            document.location = '/events/by_tutor/' + e.val;
        });
    });
</script>
<style>
    div.select2-container {
        min-width: 300px
    }
    main div.container {
        top: 50%;
        transform: translateY(-50%);
        transform: translateY(-50%);
        -o-transform: translateY(-50%);
        -ms-transform: translateY(-50%);
        -webkit-transform: translateY(-50%);
        position: relative;
    }
</style>

app/views/events/list.erb
<% content_for :sidebar do %>
    <ul class="nav nav-list">
      <% Item::SUB_TYPES.each do |k, v| %>
          <li class='newItem' data-type='<%= k.to_s %>'>
          <span>
            <%= fa_icon v.icon, class: 'fa-3x' %>
            <%= t(k.to_s+'.new') %>
          </span>
          </li>
      <% end %>
    </ul>
    <%= t 'action.add_item' %>
<% end %>

<div id="events">
  <% unless @events.blank? %>
    <% @events.group_by { |x| x.date }.sort_by{|x,y| x}.each do |date, events| %>
        <h5 class="lshift"><%= date.strftime('%e/%-m/%Y') %></h5>
        <% events.sort_by { |x| x.pair }.each do |event| %>
            <%= content_tag :div, class: 'card event', id: event.id do %>
              <div class="card-content">
                <%= render partial: 'show', locals: {event: event} %>
              </div>
            <% end %>
        <% end %>
    <% end %>
  <% else %>
  <div class="center">
      <span class="fa-stack fa-5x">
          <i class="fa fa-circle fa-stack-2x primary"></i>
          <i class="fa fa-question fa-inverse fa-stack-1x"></i>
      </span><br/>
      <h1>Пока ничего нет</h1>
  </div>
  <% end %>
</div>

app/views/events/show.erb
<%= render partial: 'show', locals: {event: @event} %>